# Generated by Django 2.1.5 on 2019-03-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_abc_empname'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('text', models.TextField(max_length=50)),
                ('content', models.CharField(default='abc', max_length=50)),
            ],
        ),
    ]
