# Generated by Django 2.1.5 on 2019-03-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
