# Generated by Django 2.1.5 on 2019-03-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.TextField(max_length=50)),
                ('empname', models.CharField(default='abc', max_length=50)),
            ],
        ),
    ]
